config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  
 

   
  namespace :api, defaults: {format: 'json'} do
    devise_for :users, path: '/users',controllers: {
      sessions: 'api/v1/custom_devise/sessions'
    }
    
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do 
      resources :users, :only => [:index]  do
        collection do
          get :users_missions
        end
      end
      resources :about_studies, :path => "mission_studies", :only => [:index,:show] 
      resources :missions 
      resources :surveys 
    end
  end
  
  
  namespace :admin do 
   resources :about_studies, :path => "mission_studies", :only => [:edit,:show,:create,:update] 
    resources :languages
    resources :missions
    resources :countries
    resources :users
       
  end
  scope '/admin' do
    mount SurveyorGui::Engine => "/surveyor_gui", :as => "surveyor_gui"
  end
  mount Surveyor::Engine => "/surveys", :as => "surveyor"
   

  root :to => "home#index"
  
  get 'home/index'
  get "/admin" => "admin/base#index", :as => "admin"
  get "/admin/surveyor_gui/surveyforms", :as => "admin_surveyforms"

  get '/assets/pictures/:id/:style/:basename.:format' => 'admin/missions#get_picture' 

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  #globalize gem
  translates :name, :description
  
  #validations
  validates_presence_of :name
  
  #Associations
  belongs_to :country 
  has_many :users_mission
  has_many :users, :through => :users_mission 
  
  has_many :surveys
  has_one :about_study
  
  has_one :picture, :as => :imageable, :class_name=>"Picture", :dependent => :destroy
  accepts_nested_attributes_for :picture
    
  # For Storing Translations - Nested Attributes
  # Reject if mission- name is enpty for any language.
  accepts_nested_attributes_for :translations, :reject_if => proc { |attributes| attributes['name'].blank? }

end

app/controllers/admin/missions_controller.rb
class Admin::MissionsController < Admin::BaseController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]
  

  # GET /admin/missions
  # GET /admin/missions.json
  def index
    @missions = Mission.all
  end

  # GET /admin/missions/1
  # GET /admin/missions/1.json
  def show 
    available_users
  end

  # GET /admin/missions/new
  def new
    @mission = Mission.new
    @mission.build_about_study
    available_users
  end

  # GET /admin/missions/1/edit
  def edit
    available_users
  end

  # POST /admin/missions
  # POST /admin/missions.json
  def create
    
    @mission = Mission.new(mission_params)
    
    #assign users to mission
    if params[:user_ids].present?
      user = params[:user_ids].delete_if{ |x| x.empty? }
      @mission.users << User.find(params[:user_ids]) 
    end
    
    
    respond_to do |format|
      if @mission.save
        format.html { redirect_to [:admin, @mission], notice: 'Mission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mission }
      else
        format.html { render action: 'new' }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/missions/1
  # PATCH/PUT /admin/missions/1.json
  def update

    available_users
    
    #assign users to mission
    if params[:user_ids].present?
      user = params[:user_ids].delete_if{ |x| x.empty? }
      @mission.users = []
      @mission.users << User.find(params[:user_ids])  
    end
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to [:admin, @mission], notice: 'Mission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/missions/1
  # DELETE /admin/missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to admin_missions_url, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	SEND_FILE_METHOD = :default

	def get_picture

		head(:not_found) and return if (track = Picture.find_by_id(params[:id])).nil?
		#head(:forbidden) and return unless track.downloadable?(current_user) 

		path = track.image.path(params[:style]) 

		head(:bad_request) and return unless File.exist?(path) && params[:format].to_s == File.extname(path).gsub(/^\.+/, '')
		contenttype = MIME::Types.type_for(path).first.content_type # => "image/gif"
		send_file_options = { :type =>  contenttype  }

		case SEND_FILE_METHOD
		  when :apache then send_file_options[:x_sendfile] = true
		  when :nginx then head(:x_accel_redirect => path.gsub(Rails.root, ''), :content_type => send_file_options[:type]) and return
		end

		send_file(path, send_file_options)
	end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:name, :description, :start_date, :end_date, :contact, :country_id, :language_id, :user_ids, :active, :translations_attributes => [:id, :locale, :name, :description], :picture_attributes =>[:id, :image, :filename] )
    end
    
    def available_users  
      @selected_users = @mission.users
      @available_users = User.team_member
      @available_users += User.team_leader
    end
end

app/controllers/api/v1/missions_controller.rb
class Api::V1::MissionsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :json
 
  def index 
    @missions = Mission.all   
  end 
  
  def show 
    @mission = Mission.find(params[:id])   
  end 

end

app/views/admin/missions/_form.html.erb
<% @languages = Language.all %>

<div class="container">
 <div class="col-md-12">
     <div class="pull-right">    
     <div class="col-md-4">    
     
     </div>   
  
     <div class="col-md-4">    
         <!-- Button trigger modal -->
         <button class="btn btn-primary btn-xs " data-toggle="modal" data-target="#myModal">
             Add Fields For Other Language
         </button>
     </div>
    </div>
 </div>
 </div>
<br/>

<%= form_for([:admin, @mission], html: { class: 'form-horizontal mission' }) do |f| %>
  <% if @mission.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@mission.errors.count, "error") %> prohibited this mission from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @mission.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

 <br/>
  <br/>

  <%# available_locales.each_pair do |locale, name_locale| -%>
  <% @languages.each do |lang| -%>
   
   <% 
   	 locale = lang.code.to_sym
  	 name_locale = lang.name
   %>

    <% if locale == I18n.locale -%>
 
		  <div class="form-group">
		    <%= f.label :mission_name, class: 'control-label col-md-2' %>
		    <div class="col-md-10">
		      <%= f.text_field :name, class: 'form-control' %> <i>(<%= name_locale %>)</i>
		    </div>
		  </div>
		  <div class="form-group">
		    <%= f.label :description, class: 'control-label col-md-2' %>
		    <div class="col-md-10">
		      <%= f.text_area :description, class: 'form-control' %> <i>(<%= name_locale %>)</i>
		    </div>
		  </div>
  
  
    <% else -%>
      <%= f.globalize_fields_for locale do |g| -%>
 
 	  <div id="language_<%= lang.id %>" style= "display:none;">
	  <div class="form-group">
	    <%= g.label :mission_name, class: 'control-label col-md-2' %>
	    <div class="col-md-10">
	      <%= g.text_field :name, class: 'form-control' %> <i>(<%= name_locale %>)</i>
	    </div>
	  </div>
	  <div class="form-group">
	    <%= g.label :description, class: 'control-label col-md-2' %>
	    <div class="col-md-10">
	      <%= g.text_area :description, class: 'form-control' %> <i>(<%= name_locale %>)</i>
	    </div>
	  </div>
  	  </div>
  
		
      <% end -%>
    <% end -%>
  <% end -%> 



  <div class="form-group">
    <%= f.label :start_date, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :start_date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_date, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :end_date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contact, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :contact, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group"> 
	    <%= f.label :country_id, class: 'control-label col-md-2' %>
    <div class="col-md-10"> 
		<%= f.collection_select :country_id, Country.order(:name), :id, :name,
{:include_blank => 'Select Country..'}, {:class => 'form-control'} %> 
    </div>
  </div>

  
 
  <div class="form-group">
    <%#= f.label :user_id, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%#= f.number_field :user_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :assign_staffs, class: 'control-label col-md-2' %>
    <div class="col-md-10">
	  <%# if !@available_users.nil? %>
	    <%= f.select(:users, @available_users.collect {|p| [ p.name, p.id ] },{:selected => @selected_users.map(&:id)}, 
	     { :multiple => true, :size => 10 ,:name => "user_ids[]", :id => "multi_select",:include_hidden => true}) %>
          
	  <%# end %>
    </div>
  </div>
		
 
  
  <div class="form-group">
    
      <%= f.label :picture, class: 'control-label col-md-2'  %>
  
    <div class="col-sm-9"> 
      <%    @mission.build_picture   if !@mission.picture  %>
      <%= f.fields_for :picture do |photo| %>      
        <%= photo.file_field :image, class: 'form-control'  %>                  
      <% end %>     
 
      <%= image_tag f.object.picture.image.url(:thumb), :style=>"width:350px;height:150px;" %>    

    </div>
  </div>  
 
  
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.label :active, for: nil do %>
        <%= f.check_box :active, :checked => true %>
        <%= Mission.human_attribute_name(:active) %>
      <% end %>
    </div>
  </div>


  <div class="form-group">
     <%= f.label :about_study,class: 'control-label col-md-2' %>
      <div class="col-sm-9"> 
      <%= link_to 'About Study', edit_admin_about_study_path(:mission_id => @mission.id)  , :class => " "  %>  
      </div> 
  </div>      
  
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10"> 
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-vertical-centered">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Available Languages</h4>
      </div>
      <div class="modal-body">
		  <div class="row">
       
		  <% @languages.each do |lang| -%>
		   
		   <% if lang.code.to_sym != I18n.locale %>
		    <div class="col-md-3">
		  	<input type="checkbox" name="vehicle" value="Bike" id="checkbox_<%= lang.id %>" class="language-checkbox">  
			<%= lang.name %> 
			</div>
			<% end %>
		  <% end %>
		  
	  	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> 
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

	 
	
<script type="text/javascript">
	$('#multi_select').multiSelect();
	$(".language-checkbox").change(function() {
		var l_id = $(this).attr('id').split("_")[1];
	    if(this.checked) { 
			$("#language_"+l_id).show(); 
			
	    }else
		{ 	
			$("#language_"+l_id).hide();
		}
	});
</script>

app/views/admin/missions/edit.html.erb
<div class="page-header">
  <h1>Editing mission</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @mission], class: 'btn btn-default' %>
<%= link_to 'Back', admin_missions_path, class: 'btn btn-default' %>

app/views/admin/missions/index.html.erb
<div class="page-header">
  <h3>Listing missions</h3>
  <%= database_language_links %>
</div>

<div class="form-group">
<table class="sortable table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th> 
      <th>Start date</th>
      <th>End date</th>
      <th>Contact</th>
      <th>Country</th>  
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.name %></td> 
        <td><%= mission.start_date %></td>
        <td><%= mission.end_date %></td>
        <td><%= mission.contact %></td>
        <td><%= mission.country.name rescue '' %></td>  
        <td><%= mission.active %></td>
        <td><%= link_to 'Show', [:admin, mission], class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_mission_path(mission), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', [:admin, mission], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mission', new_admin_mission_path, class: 'btn btn-primary' %>
</div>

app/views/admin/missions/new.html.erb
<div class="page-header">
  <center><h3>New mission</h3></center>
  
</div>

<div class="col-md-8">
<%= render 'form' %>

<%= link_to 'Back', admin_missions_path, class: 'btn btn-default' %>
</div>

app/views/admin/missions/show.html.erb
 

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @mission.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Description:</strong></dt>
  <dd><%= @mission.description %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Start date:</strong></dt>
  <dd><%= @mission.start_date %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>End date:</strong></dt>
  <dd><%= @mission.end_date %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Contact:</strong></dt>
  <dd><%= @mission.contact %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Country:</strong></dt>
  <dd><%= @mission.country.name rescue '' %></dd>
</dl>

 

<dl class="dl-horizontal">
  <dt><strong>Assigned Members:</strong></dt>
  <dd>
	  <%  @mission.users.each do |user| %>
	  <%= link_to user.name, admin_user_path(user) %>
	  <% end %>
  </dd>
</dl>


<dl class="dl-horizontal">
  <dt><strong>Surveys:</strong></dt>
  <dd>
	  <%  @mission.surveys.each do |survey| %>
	  <%= link_to survey.title, surveyor_gui.edit_surveyform_path(survey) %>
	  <% end %>
  </dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Active:</strong></dt>
  <dd><%= @mission.active %></dd>
</dl>

<%= link_to 'Edit', edit_admin_mission_path(@mission), class: 'btn btn-default' %>
<%= link_to 'Back', admin_missions_path, class: 'btn btn-default' %>