config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  
 

   
  namespace :api, defaults: {format: 'json'} do
    devise_for :users, path: '/users',controllers: {
      sessions: 'api/v1/custom_devise/sessions'
    }
    
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do 
      resources :users, :only => [:index]  do
        collection do
          get :users_missions
        end
      end
      resources :about_studies, :path => "mission_studies", :only => [:index,:show] 
      resources :missions 
      resources :surveys 
    end
  end
  
  
  namespace :admin do 
   resources :about_studies, :path => "mission_studies", :only => [:edit,:show,:create,:update] 
    resources :languages
    resources :missions
    resources :countries
    resources :users
       
  end
  scope '/admin' do
    mount SurveyorGui::Engine => "/surveyor_gui", :as => "surveyor_gui"
  end
  mount Surveyor::Engine => "/surveys", :as => "surveyor"
   

  root :to => "home#index"
  
  get 'home/index'
  get "/admin" => "admin/base#index", :as => "admin"
  get "/admin/surveyor_gui/surveyforms", :as => "admin_surveyforms"

  get '/assets/pictures/:id/:style/:basename.:format' => 'admin/missions#get_picture' 

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  

end

app/models/surveyor_gui/attribute_permitter.rb
module AttributePermitter
  # survey_attributes base method found in surveyor gem.
  # surveyor_gui gem override's survey_attributes method.
  # We extend method to include our parameters.  
  # More Details http://blog.jayfields.com/2008/04/alternatives-for-redefining-methods.html
  def survey_attributes
    super + [:mission_id]
  end
end   

app/controllers/surveyor_gui/surveyforms_controller.rb
class SurveyorGui::SurveyformsController < Admin::BaseController
  include Surveyor::SurveyorControllerMethods
  include SurveyorGui::SurveyformsControllerMethods
  
  
  def create
    @surveyform = Surveyform.new(surveyforms_params.merge(user_id: @current_user.nil? ? @current_user : @current_user.id))
 
    
    if @surveyform.save
      flash[:notice] = "Successfully created survey."
      @title = "Edit Survey"
      @question_no = 0
      redirect_to edit_surveyform_path(@surveyform.id)
    else
      render :action => 'new'
    end
  end
  
  
  def destroy
    @surveyform = Surveyform.find(params[:id])
    response_sets_total = @surveyform.response_sets.count
    
      if response_sets_total > 0
        flash[:error] = 'This survey has responses and can not be deleted' 
      elsif response_sets_total== 0
        if @surveyform.destroy
          flash[:notice] = "Successfully destroyed survey." 
        else
          flash[:error] = "Problem Deleting survey." 
        end
      else
        flash[:error] = 'Survey could not be deleted.'
      end
      redirect_to surveyforms_url
    
  end
  

  private
  def surveyforms_params
    ::PermittedParams.new(params[:surveyform]).extend(AttributePermitter).survey
  end
  
  
 

end

app/views/surveyor_gui/surveyforms/_form.html.erb
<div id="box" class="boxshadow round">
  <div class="column3">
    <input id='pass_cbox_data' type="hidden">
    <div class="shadebox round">
      <div id="survey">
        <h3 class="round-top">
          <%= @title %>
            <% if @surveyform.id -%>
              <input class="btn btn-warning btn-xs " onclick="preview_cbox('<%= surveyor_gui.survey_url(@surveyform.id) %>',
                <%= @surveyform.id %>);" type="button" value="Preview Survey" />
              <input class="btn btn-warning btn-xs" onclick="preview_cbox('<%= surveyor_gui.preview_response_url(@surveyform.id) %>', 
                <%= @surveyform.id %>);" type="button" value="Preview Response" />
              <input class="btn btn-warning btn-xs" onclick="preview_cbox('<%= surveyor_gui.preview_report_url(@surveyform.id) %>', 
                <%= @surveyform.id %>);" type="button" value="Preview Report" />
            <% end %>
        </h3>
 
        <%= simple_form_for [surveyor_gui, @surveyform]  do |f| %>
          <%#= f.error_messages %>
		  
		  <% if @surveyform.errors.any? %>
		    <div id="error_explanation" class="panel panel-danger">
		      <div class="panel-heading">
		        <h2 class="panel-title"><%= pluralize(@surveyform.errors.count, "error") %> prohibited this mission from being saved:</h2>
		      </div>
		      <div class="panel-body">
		        <ul>
		        <% @surveyform.errors.full_messages.each do |msg| %>
		          <li><%= msg %></li>
		        <% end %>
		        </ul>
		      </div>
		    </div>
		  <% end %>
		  
          <br/>
          <%= f.hidden_field :id %>
		  
		  
		   <div class="col-md-1"> 
          <%= f.label :title, :required => false,  :style => 'font-size: 150%; ' , :class => "control-label" %>
	  	  </div>
		   <div class="col-md-6">
          <%= f.input :title, :input_html => { :size => '35', :style=>'margin-top: 0.5%; font-size: 110%; float:left;'}, :required=>false , :label=>false %>
	       </div>
		   	
		   <div class="col-md-2">
          <%= f.label :mission, :required => false,  :style => 'font-size: 150%; ' , :class => "control-label" %>
    	  </div>
		  <div class="col-md-3">
		  	<%= f.collection_select :mission_id, Mission.order(:name), :id, :name,
		  {:include_blank => 'Select Mission..'}, {:class => 'form-control'} %>
	  	  </div> 
		  
		  <br/> 
		  <br/> 
			   
		   <div class="pull-right">
			   <div class="col-md-6">
          <%= f.input :template, :disabled=>@survey_locked, :label => false, :input_html=>{:style=>"float:right;"} %>
	      </div>
	      <div class="col-md-6">
           <span style='position:relative; float: right;'>Template?  &nbsp;
           </span>
	      </div>
	  	  </div>
		  <br/><br />
          <div class="sortable_sections" data-survey_locked=<%= @survey_locked %>>
            <%= render "survey_section_fields", :s => builder , :f => f %>
          </div>
          <% if @survey_locked%>
            <p><button class="go_back" type="button">Go Back</button></p>
          <% else -%>
            <p><%= f.button :submit,  'Save Changes'  ,:class => 'btn btn-primary' %></p>
          <% end -%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function preview_cbox(url, id) {
    $.colorbox({width:"90%",
                height:"90%",
                scrolling:true,
                iframe:true,
                href: url + '?suppress_header=true&survey_id='+ id,
                opacity:.3});
  }
</script>

app/views/surveyor_gui/surveyforms/_question_field.html.erb
<%= f.hidden_field :id %>
<%= f.hidden_field :display_order %>
<%= f.hidden_field :modifiable %>

<%= row_label_if_question_group f.object %>

<% question_type = f.object.question_type_id
   case question_type
     when :slider -%>
      <div class="slider">
      <!-- The slider uses the Jquery UISlider plugin (http://www.filamentgroup.com/lab/update_jquery_ui_16_slider_from_a_select_element/) -->
      <!-- Look in application.js for the hook - it selects all input select elements with "uislider" as the class -->
      <%= f.input :dummy_answer, :collection => f.object.answers.map{|a| a.text}, :as => :select, :label => false,
                  :input_html => {:class => "uislider"}, :include_blank => false, :wrapper_html=>{:class => 'shrink_slider'} %>
      </slider>
  <% when :stars -%>
    <%= f.input :dummy_answer, label: false, :collection => [[nil,1],[nil,2],[nil,3],[nil,4],[nil,5]],
                :as => :radio_buttons, :input_html=>{:class=>'star'}, :wrapper_html=>{:class=>'star'} %>

  <% when :pick_one -%>

    <% f.object.answers.each do |answer| -%>
      <% if answer.is_comment==true -%>
          <span class="other comments_text">
            <%= f.input :dummy_answer,  :as=>:string, label: answer.text %>
          </span>
      <% else -%>
        <%= f.input_field :dummy_answer, label: (f.object.repeater? ? answer.text : false), collection: [answer.text], collection: [answer.text], :as => :radio_buttons%>
        <% if answer.response_class == "string" %>
          <span class="other">
            <%= f.input_field :dummy_answer,  :as=>:string, :label=> false%>
          </span>
        <% end -%>
      <% end -%>
    <% end -%>

  <% when :grid_one -%>

    <% f.object.answers.each do |answer| -%>
      <%= f.input_field :dummy_answer, label: false, collection: [answer.text], :as => :radio_buttons %>
      <% if answer.response_class == "string" %>
        <span class="other">
          <%= f.input_field :dummy_answer,  :as=>:string, :label=>false%>
        </span>
      <% end -%>
    <% end -%>

  <% when :dropdown -%>

    <%= f.input :dummy_answer, label: false, :collection => f.object.answers.collect(&:text), :as => :select %>


  <% when :grid_dropdown -%>
    <% f.object.question_group.columns.each do |column|  %>
      <%= f.input :dummy_answer, label: false,
                  :collection => f.object.answers.where('column_id=?',column.id).collect(&:text),
                  :as => :select, :wrapper_html=>{:class=>'grid_dropdown_cell'} %>
    <% end -%>

  <% when :pick_any %>
    <% f.object.answers.each do |answer| -%>
      <% if answer.is_comment==true -%>
          <span class="other comments_text">
            <%= f.input :dummy_answer,  :as=>:string, label: answer.text %>
          </span>
      <% else -%>
        <%= f.input_field :dummy_answer_array, label: (f.object.repeater? ? answer.text : false), collection: [answer.text], :as => :check_boxes %>
        <% if answer.response_class == "string" %>
          <span class="other">
            <%= f.input_field :dummy_answer,  :as=>:string, :label=> false%>
          </span>
        <% end -%>
      <% end -%>
    <% end -%>

  <% when :grid_any %>

    <% if f.object.dynamically_generate==false -%>
      <br />
      <span style="font-weight:normal;font-style:italic" class="field_indent">content retrieved from the application will go here.</span>
      <br />
    <% else -%>
      <% f.object.answers.each do |answer| -%>
        <%= f.input_field :dummy_answer_array, label: false, collection: [answer.text], :as => :check_boxes %>
        <% if answer.response_class == "string" %>
          <span class="other">
            <%= f.input_field :dummy_answer,  :as=>:string, :label=>false%>
          </span>
        <% end -%>
      <% end -%>

    <% end %>

  <% when :label -%>
     <span style="margin-left: 4.5em;">
     <%= f.object.text %>
     </span>

  <% when  :string -%>
    <%= f.input :dummy_answer, :as=>:string, :label=>false, :input_html=>{:rows=>"1"}%>

  <% when  :box -%>

    <%= f.input :dummy_answer, :as=>:text, :label=>false, :input_html=>{ :rows=>"3"}%>

  <% when :number -%>
    <!-- Prefix -->
    <span class="fl prefix">
      <% if f.object.answers.first.text.include?('|') %>
        <%= f.object.answers.first.text.split('|')[0] %>&nbsp;
      <% end %>
    </span>

    <!-- Number -->
    <%= f.input :dummy_answer, :as=>:string, :label=>false, :input_html=>{:size=>"10"}, :wrapper_html=>{:class=>'fl notfirst number'} %>

    <!-- Suffix -->
    <span class="suffix fl">
      &nbsp;
      <%= f.object.answers.first.text.split('|')[1] %>
    </span>
  <% when :date -%>
      <%= f.input :dummy_answer, :as=>:date_picker, :label=>false, :input_html=>{:size => "8",:style=>"margin-left: 4.5em;"},
                  :hint => 'mm/dd/yy', :hint_html=>{:style=>'margin-left:5em;'} %>

  <% when :datetime -%>
      <%= f.input :dummy_answer, :as=>:datetime_picker, :label=>false, :input_html=>{:size => "8",:style=>"margin-left: 4.5em;"},
                  :hint => 'mm/dd/yy hh:mm', :hint_html=>{:style=>'margin-left:5em;'} %>

  <% when :time -%>
      <%= f.input :dummy_answer, :as=>:time_picker, :label=>false, :input_html=>{:size => "8",:style=>"margin-left: 4.5em;"},
                  :hint => 'hh:mm', :hint_html=>{:style=>'margin-left:5em;'} %>
  <% when :file -%>
    <%= f.input :dummy_blob, :as => :file, :label=>false, :input_html=>{:size => "8",:style=>"margin-left: 4.5em;"} %>

  <% else -%>
    <br/>
    <br />
    <%= f.input :dummy_answer, :label=>false, :input_html=>{:style=>"margin-left: 4.5em;"}%>
<% end -%>

<% if !f.object.modifiable? -%>
  <br />
  <span class='field_indent'>
    Report Code: <%= f.object.report_code %>
  </span>
  <br />
<% end %>

app/views/surveyor_gui/surveyforms/_question_group.html.erb
<% @question_no = @question_no + 1 if f.object.id && f.object.question_type != 'Label'-%>
<%= div_for(f.object) do %>
  <fieldset class="question_group_area_background_fs 
    fields
    questions
    <%= f.object.is_mandatory ? 'mandatory_questions' : 'optional_questions' %>
    <%= !@survey_locked && (f.object.modifiable) ? '' : 'not_modifiable' %>"
  >
    <div class="inner_question " >
      <!-- if dependencies, notify the user with a highlighted message at the top of the question -->
      <% if f.object.question_group.dependent? -%>
        <span class="question_logic_notifier">
          <!-- list_dependencies tells the user which other questions determine whether this one is displayed -->
          <%= list_dependencies(f.object.question_group) if f.object.question_group.dependent?  rescue ''%>.<br/>
        </span>
      <% end -%>

      <!-- display the button bar unless a user has already submitted responses, thus locking the survey, or   -->
      <!-- the survey is explicitly marked not modifiable (e.g., an administrator locks it).                   -->
      <% if !@survey_locked && (f.object.modifiable?) -%>
        <span class="fl ui-icon ui-icon-arrowthick-2-n-s"></span>

        <span class="question_button_bar pull-right">

          <button type="button" id="edit_question" class="btn btn-default btn-xs" 
             data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(
              id:           f.object.survey_section.survey.id,
              question_id:  f.object.id)%>"
             data-edit_question_url="<%= (f.object.part_of_group? && f.object.question_group.display_type != 'grid') ? surveyor_gui.edit_question_group_url(f.object.question_group.id) : surveyor_gui.edit_question_url(f.object.id)%>"
             data-question_id="<%= f.object.id.to_s %>"
          >Edit Question</button>

          <button type="button" id="cut_question" class="btn btn-default btn-xs" 
             data-cut_question_surveyform_url="<%=surveyor_gui.cut_question_surveyform_url(
              id:           f.object.survey_section.survey.id,
              question_id:  f.object.id)%>"
             data-question_already_cut="<%= session[:cut_question] %>"
          >Cut Question</button>

          <button type="button" id="delete_question" class="btn btn-default btn-xs" 
             data-question_url="<%=surveyor_gui.question_url(f.object.id)%>"
             data-replace_form_surveyform_url="<%= surveyor_gui.replace_form_surveyform_url(
              id:                 f.object.survey_section.survey.id,
              survey_section_id:  f.object.survey_section_id) %>"
          >Delete Question</button>

          

            <% if f.object.question_group.dependent? -%>

              <button type="button" id="delete_logic" class="btn btn-default btn-xs" 
                 data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(:question_id => f.object.id)%>"
                 data-dependency_url="<%= surveyor_gui.dependency_url(f.object.id) %>"
                 data-question_id="<%= f.object.id.to_s %>"
              >Delete Logic</button>


              <button type="button" id="edit_logic" class="btn btn-default btn-xs" 
                data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(:question_id => f.object.id)%>"
                data-edit_dependency_url="<%= surveyor_gui.edit_dependency_url(f.object.id) %>"
                data-question_id="<%= f.object.id.to_s %>"
              >Edit Logic</button>

            <% else -%>
                <button type="button" id="add_logic" class="btn btn-default btn-xs" 
                  data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(
                    id:           f.object.survey_section.survey.id,
                    question_id:  f.object.id)%>"
                  data-new_dependency_url="<%= surveyor_gui.new_dependency_url(:id=>f.object.id) %>"
                  data-question_id="<%= f.object.id.to_s %>"
                >Add Logic</button>
            <% end %>

          
        </span>

      <% end %>
      <br />
      <br />
      <%= render "question_name_and_number", question_type: f.object.question_type, text: f.object.question_group.text %>
      <br />
      <div class="question_group <%= question_group_class(f.object) %> <%= f.object.repeater? ? "repeater" : nil %>">
        <div class="question_group_header">
          <span class="question_group_heading">&nbsp;</span>
          <%= question_group_heading(f) %>
        </div>
        <%= render_one_group ss -%>
      </div>

    </div>
  </fieldset>

  <% if !@survey_locked && (f.object.modifiable?) -%>

    <div class="question_buttons_bottom">

      <button type="button" id="add_question" class="cut btn btn-primary btn-xs" 
        data-insert_new_question_url="<%=surveyor_gui.insert_new_question_surveyform_url(id: f.object.survey_section.survey.id, ) %>"
        data-new_question_url="<%=surveyor_gui.new_question_url%>"
        data-prev_question_id="<%= f.object.id.to_s %>"
      >Add Question</button>

      <% if session[:cut_question] -%>

        <button type="button" id="paste_question" class=" btn btn-primary btn-xs" 
          data-paste_question_surveyform_url="<%= surveyor_gui.paste_question_surveyform_url(
              id:           f.object.survey_section.survey.id,
              question_id:  f.object.id) %>"
        >Paste Question</button>

      <% end %>

    </div>

  <% end %>
<% end %>

app/views/surveyor_gui/surveyforms/_question_group_fields.html.erb
<div class="question_group_element">
  <%= render "question_field", f: f %>
</div>

app/views/surveyor_gui/surveyforms/_question_name_and_number.html.erb
<!-- Tack a number onto questions, e.g. "3) What is your name?" but don't do it for labels -->
<% if question_type.id != :label -%>
  <span class="questions ">
    <%= (@question_no.to_s+ ') ' + text.to_s)%>
  </span>
<% end %>

app/views/surveyor_gui/surveyforms/_question_section.html.erb
<!-- this code makes it possible to call this part of the view from either an ajax call
or a reference from the survey_sections.html.erb -->
<% if local_assigns[:f] -%>
  <%= render_questions_and_groups_helper q, s -%>
<% else -%>
  <%= simple_fields_for 'surveyform', @question.survey_section.survey do |sf| %>
    <%= sf.simple_fields_for :survey_sections do |ss| %>
    <% end %>
    <%= sf.simple_fields_for :survey_sections, @question.survey_section do |ss| %>
      <%= ss.simple_fields_for :questions, @question do |q| %>
        <%= render_questions_and_groups_helper q, ss -%>
      <% end %>
    <% end %>
  <% end %>
<% end -%>

app/views/surveyor_gui/surveyforms/_question_wrapper.html.erb
<% @question_no = @question_no + 1 if f.object.id && f.object.question_type_id != :label -%>
<%= div_for(f.object) do %>
  <fieldset class="question_area_background_fs 
    fields
    questions
    <%= f.object.is_mandatory ? 'mandatory_questions' : 'optional_questions' %>
    <%= !@survey_locked && (f.object.modifiable) ? '' : 'not_modifiable' %>"
  >
    <div class="inner_question " >
      <!-- if dependencies, notify the user with a highlighted message at the top of the question -->
      <% if f.object.dependent? -%>
        <span class="question_logic_notifier">
          <!-- list_dependencies tells the user which other questions determine whether this one is displayed -->
          <%= list_dependencies(f.object) if f.object.dependency %>.<br/>
        </span>
      <% end -%>

      <!-- display the button bar unless a user has already submitted responses, thus locking the survey, or   -->
      <!-- the survey is explicitly marked not modifiable (e.g., an administrator locks it).                   -->
      <% if !@survey_locked && (f.object.modifiable?) -%>
        <span class="fl ui-icon ui-icon-arrowthick-2-n-s"></span>

        <span class="question_button_bar pull-right" >

          <button type="button" id="edit_question"  class="btn btn-default btn-xs"
             data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(id: f.object.survey_section.survey.id, 
              question_id:  f.object.id)%>"
             data-edit_question_url="<%=surveyor_gui.edit_question_url(f.object.id)%>"
             data-question_id="<%= f.object.id.to_s %>"
          >Edit Question</button>

          <button type="button" id="cut_question" class="btn btn-default btn-xs"
             data-cut_question_surveyform_url="<%=surveyor_gui.cut_question_surveyform_url(
              id:           f.object.survey_section.survey.id, 
              question_id:  f.object.id)%>"
             data-question_already_cut="<%= session[:cut_question] %>"
          >Cut Question</button>

          <button type="button" id="delete_question" class="btn btn-default btn-xs"
             data-question_url="<%=surveyor_gui.question_url(f.object.id)%>"
             data-replace_form_surveyform_url="<%= surveyor_gui.replace_form_surveyform_url(
              id:                 f.object.survey_section.survey.id, 
              survey_section_id:  f.object.survey_section_id) %>"
          >Delete Question</button>

          <span style="">

            <% if f.object.dependent? -%>

              <button type="button" id="delete_logic" class="btn btn-warning btn-xs"
                 data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(:question_id => f.object.id)%>"
                 data-dependency_url="<%= surveyor_gui.dependency_url(f.object.id) %>"
                 data-question_id="<%= f.object.id.to_s %>"
              >Delete Logic</button>


              <button type="button" id="edit_logic" class="btn btn-warning btn-xs"
                data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(:question_id => f.object.id)%>"
                data-edit_dependency_url="<%= surveyor_gui.edit_dependency_url(f.object.id) %>"
                data-question_id="<%= f.object.id.to_s %>"
              >Edit Logic</button>

            <% else -%>
                <button type="button" id="add_logic" class="btn btn-warning btn-xs"
                  data-replace_question_url="<%=surveyor_gui.replace_question_surveyform_path(
                    id:           f.object.survey_section.survey.id, 
                    question_id:  f.object.id)%>"
                  data-new_dependency_url="<%= surveyor_gui.new_dependency_url(:id=>f.object.id) %>"
                  data-question_id="<%= f.object.id.to_s %>"
                >Add Logic</button>
            <% end %>

          </span>
        </span>

      <% end %>
 
	  
	  
		  <div class="col-md-12">
			  <div class="form-group">
			  <b>
		  <%= render "question_name_and_number", question_type: f.object.question_type, text: f.object.text %>
		  	</b> 
			</div>
			<div class="form-group">
	      	<%= render "question_field", f: f %>
			 </div>
	  	  </div>
	 
    </div>
  </fieldset>

  <% if !@survey_locked && (f.object.modifiable?) -%>

	<div class="row question_bottom_buttons_fs">
		 
			
     <div class="question_buttons_bottom " >

      <button type="button" id="add_question" class="cut btn btn-primary btn-xs"
        data-insert_new_question_url="<%=surveyor_gui.insert_new_question_surveyform_url(id: f.object.survey_section.survey.id, ) %>"
        data-new_question_url="<%=surveyor_gui.new_question_url%>"
        data-prev_question_id="<%= f.object.id.to_s %>"
      >Add Question</button>

      <% if session[:cut_question] -%>

        <button type="button" id="paste_question" class="btn btn-primary btn-xs"
          data-paste_question_surveyform_url="<%= surveyor_gui.paste_question_surveyform_url(
              id:           f.object.survey_section.survey.id,
              question_id:  f.object.id) %>"
        >Paste Question</button>

      <% end %> 
 
    </div>
	</div>
  <% end %>
<% end %>

app/views/surveyor_gui/surveyforms/clone_survey.html.erb
<div class="column3">
  <div class="shadebox round">
    <div id="survey">
        <h1 class="round-top"><%= @title %></h1>
        <%= simple_form_for @surveyform, :url => create_cloned_surveyform_path do |f| %>
          <%= f.error_messages %>
          <%= f.hidden_field :id %>
          <%= f.input :title, :label => "New Title",:hint => 'Name this survey, questionnaire, or form', :input_html=>{:style=>'width:25em;'}, :label_html=>{:style=>'width:6em;'}%>
          <%= f.button :submit, @title %>
      <% end %>
    </div>
  </div>
</div>

app/views/surveyor_gui/surveyforms/edit.html.erb
<%= render 'form' %>
  <p class="floatdown">
    <%= link_to "Show", surveyor_gui.surveyform_path(@surveyform) %> |
    <%= link_to "View All", surveyor_gui.surveyforms_path %>
  </p>

app/views/surveyor_gui/surveyforms/index.html.erb
<div class="column2">
  <div class="shadebox round">
  <div id="survey">
    <h1 class="round-top"><%= @title %></h1>
      <%= form_tag surveyforms_path, :method => 'get'  do %>
        <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil , :class=> "btn btn-default" %>
        </p>
    <% end %>
  <%= will_paginate %>
  <br />
<table class="table table-bordered ">
  <tr>
    <th>Title</th>
    <th>Version</th>
	<th>Responses</th>
    <th>Actions</th>
  </tr>
  <% for survey in @surveyforms %>
    <tr>
      <td><%= survey.title %></td>
      <td><%= survey.survey_version %></td>
	  <td><%= survey.response_sets.count %></td>
      <td><%= link_to "Show", survey, class: 'btn btn-xs btn-default' %>&nbsp
      <%= link_to "Edit", edit_surveyform_path(survey), class: 'btn btn-xs btn-warning' %>&nbsp
      <%= link_to "Clone", clone_survey_surveyform_path(survey), class: 'btn btn-xs btn-info' %>&nbsp
      <%= link_to "Destroy", survey, data: { confirm: 'Are you sure?' }, :method => :delete, class: 'btn btn-xs btn-danger' %>&nbsp; 
      <%= link_to "Run Report", report_path(survey), class: 'btn btn-xs btn-primary' %> &nbsp;
      <%= link_to "View Responses" , responses_path(id: survey), class: 'btn btn-xs btn-success' %></td>
    </tr>
  <% end %>
</table>
<br />
<%= will_paginate %>
<p>
  <%= link_to "New Survey", new_surveyform_path()  , :class=> "btn btn-default" %>&nbsp
  <%= link_to "Take a Survey", surveyor.available_surveys_path  , :class=> "btn btn-default" %>&nbsp
</p>
</div>
  </div>
</div>

app/views/surveyor_gui/surveyforms/new.html.erb
<%= render 'form' %>

app/views/surveyor_gui/surveyforms/show.html.erb
<%= render 'form' %>
  <p class="floatdown">
    <%= link_to "Edit", edit_surveyform_path(@surveyform.id) %>&nbsp |
    <%= link_to "View All", surveyforms_path %>
  </p>