config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  
 

   
  namespace :api, defaults: {format: 'json'} do
    devise_for :users, path: '/users',controllers: {
      sessions: 'api/v1/custom_devise/sessions'
    }
    
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do 
      resources :users, :only => [:index]  do
        collection do
          get :users_missions
        end
      end
      resources :about_studies, :path => "mission_studies", :only => [:index,:show] 
      resources :missions 
      resources :surveys 
    end
  end
  
  
  namespace :admin do 
   resources :about_studies, :path => "mission_studies", :only => [:edit,:show,:create,:update] 
    resources :languages
    resources :missions
    resources :countries
    resources :users
       
  end
  scope '/admin' do
    mount SurveyorGui::Engine => "/surveyor_gui", :as => "surveyor_gui"
  end
  mount Surveyor::Engine => "/surveys", :as => "surveyor"
   

  root :to => "home#index"
  
  get 'home/index'
  get "/admin" => "admin/base#index", :as => "admin"
  get "/admin/surveyor_gui/surveyforms", :as => "admin_surveyforms"

  get '/assets/pictures/:id/:style/:basename.:format' => 'admin/missions#get_picture' 

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :missions
  has_many :languages
  
  #validations
  validates_presence_of :name
  validates_presence_of :code
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::BaseController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /admin/countries
  # GET /admin/countries.json
  def index
    @countries = Country.all
  end

  # GET /admin/countries/1
  # GET /admin/countries/1.json
  def show
  end

  # GET /admin/countries/new
  def new
    @country = Country.new
  end

  # GET /admin/countries/1/edit
  def edit
  end

  # POST /admin/countries
  # POST /admin/countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to [:admin, @country], notice: 'Country was successfully created.' }
        format.json { render action: 'show', status: :created, location: @country }
      else
        format.html { render action: 'new' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/countries/1
  # PATCH/PUT /admin/countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to [:admin, @country], notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/countries/1
  # DELETE /admin/countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to admin_countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :code)
    end
end

app/views/admin/countries/_form.html.erb
<%= form_for([:admin, @country], html: { class: 'form-horizontal country' }) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group"  >
    <%= f.label :select_country, class: 'control-label col-md-2' %>
    <div class="col-md-10">
        <%= country_code_select(:country, :code ,{},{} , { :onchange => 'update_country_name()', :id=>"country_select",:class => 'form-control'})  %>
    </div>
  </div>

  
  <div class="form-group" style="display:none;">
    <%= f.label :name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, class: 'form-control', :id =>"country_name" %> 
    </div>
  </div>
  <div class="form-group" style="display:none;">
    <%= f.label :code, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :code, class: 'form-control', :id =>"country_code" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script>
function update_country_name()
{
	var c_name =  $("#country_select option:selected").text();
	var c_code = $("#country_select").val();
	$("#country_name").val(c_name);
	$("#country_code").val(c_code);
	
}
	
 
</script>

app/views/admin/countries/edit.html.erb
<div class="page-header">
  <h1>Editing country</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @country], class: 'btn btn-default' %>
<%= link_to 'Back', admin_countries_path, class: 'btn btn-default' %>

app/views/admin/countries/index.html.erb
<div class="page-header">
  <h3>Listing countries</h3>
</div>
 
  <div class="row">
      <div class="col-md-12"> 
          <%= link_to 'New Country', new_admin_country_path, class: 'btn btn-warning', :style =>"float:right;" %>
      </div> 
  </div>  
  <br/>
<table class="sortable table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.code %></td>
        <td><%= link_to 'Show', [:admin, country], class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_country_path(country), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', [:admin, country], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/countries/new.html.erb
<div class="page-header">
  <h1>New country</h1> 
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_countries_path, class: 'btn btn-default' %>

app/views/admin/countries/show.html.erb
 
<br/>
<br/>
<br/>
<br/>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @country.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Code:</strong></dt>
  <dd><%= @country.code %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Mission's:</strong></dt>
  <dd>
  <ul> 
  <% @country.missions.each do |mission| %> 
  	 <li><%= link_to mission.name, admin_mission_path(mission) %>  </li>
  <% end %>
  </ul>
  </dd>
</dl>

<br/>
<br/>
<br/>
<br/>
<br/>



<%= link_to 'Edit', edit_admin_country_path(@country), class: 'btn btn-default' %>
<%= link_to 'Back', admin_countries_path, class: 'btn btn-default' %>